FROM hypriot/rpi-alpine-scratch:v3.3

# Install dependencies
RUN apk add -U \
    python \
    python-dev \
    py-pip \
    py-virtualenv

# Define working directory
WORKDIR /data

# Define default command
CMD ["/bin/sh"]
